import { existsSync } from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { GoogleAuth } from "google-auth-library";
import type { AppConfig } from "./types.js";

const ENV_CANDIDATES = [
  path.resolve(process.cwd(), ".env"),
  path.resolve(process.cwd(), "../.env")
];

for (const envPath of ENV_CANDIDATES) {
  if (existsSync(envPath)) {
    dotenv.config({ path: envPath, override: false });
  }
}

const DEFAULT_PORT = 8787;
const DEFAULT_LOCATION = "global";
const DEFAULT_MODEL = "gemini-2.5-flash";
const DEFAULT_STOREFRONT = "us";
const DEFAULT_DESCRIPTION = "Generated by Apple Music Playlist Builder";

function toPositiveInteger(value: string | undefined, fallback: number): number {
  if (!value) {
    return fallback;
  }

  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return fallback;
  }

  return parsed;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

async function resolveGoogleProjectId(): Promise<string | undefined> {
  try {
    const auth = new GoogleAuth({
      scopes: ["https://www.googleapis.com/auth/cloud-platform"]
    });

    const projectId = await auth.getProjectId();
    return projectId ?? undefined;
  } catch {
    return undefined;
  }
}

export async function loadConfig(): Promise<AppConfig> {
  const port = toPositiveInteger(process.env.PORT, DEFAULT_PORT);
  const projectId =
    process.env.GOOGLE_CLOUD_PROJECT ||
    process.env.GCLOUD_PROJECT ||
    (await resolveGoogleProjectId());

  return {
    port,
    google: {
      projectId,
      location: process.env.GOOGLE_CLOUD_LOCATION || DEFAULT_LOCATION,
      model: process.env.VERTEX_MODEL || DEFAULT_MODEL
    },
    apple: {
      teamId: process.env.APPLE_MUSIC_TEAM_ID,
      keyId: process.env.APPLE_MUSIC_KEY_ID,
      privateKeyPath: process.env.APPLE_MUSIC_PRIVATE_KEY_PATH,
      tokenTtlMinutes: clamp(
        toPositiveInteger(process.env.APPLE_MUSIC_TOKEN_TTL_MINUTES, 60),
        5,
        1440
      ),
      defaultStorefront:
        process.env.APPLE_MUSIC_STOREFRONT || DEFAULT_STOREFRONT,
      defaultDescription:
        process.env.PLAYLIST_DEFAULT_DESCRIPTION || DEFAULT_DESCRIPTION
    }
  };
}
